# 基于您提供的配置信息创建的模型配置文件
# 复制到 ~/.mito-forge/model_profiles.yaml 使用

# OpenAI 配置（通过 ChatAnywhere 代理）
openai-chatanywhere:
  provider_type: openai
  model: gpt-4o-mini
  api_key: sk-dXNuGDs3KotAklMIskLrcaX2jiexm90d4WfODZwkjXi1Yj28
  api_base: https://api.chatanywhere.tech/v1
  description: OpenAI via ChatAnywhere 代理

# 硅基流动配置（GUIJI）
siliconflow-qwen:
  provider_type: openai_compatible
  model: Qwen/Qwen2.5-7B-Instruct
  api_key: sk-htxxabglzxtqokjwvfoiidprglsvnqffxshgognjafvgcwov
  api_base: https://api.siliconflow.cn/v1
  description: 硅基流动 Qwen 模型

# Supervisor 专用配置
supervisor-openai:
  provider_type: openai
  model: gpt-4o-mini
  api_key: sk-dXNuGDs3KotAklMIskLrcaX2jiexm90d4WfODZwkjXi1Yj28
  api_base: https://api.chatanywhere.tech/v1
  description: Supervisor Agent 专用 OpenAI

supervisor-qwen:
  provider_type: openai_compatible
  model: Qwen/Qwen2.5-7B-Instruct
  api_key: sk-htxxabglzxtqokjwvfoiidprglsvnqffxshgognjafvgcwov
  api_base: https://api.siliconflow.cn/v1
  description: Supervisor Agent 专用 Qwen

# Expert 专用配置
expert-openai:
  provider_type: openai
  model: gpt-4o-mini
  api_key: sk-dXNuGDs3KotAklMIskLrcaX2jiexm90d4WfODZwkjXi1Yj28
  api_base: https://api.chatanywhere.tech/v1
  description: Expert Agent 专用 OpenAI

expert-qwen:
  provider_type: openai_compatible
  model: Qwen/Qwen2.5-7B-Instruct
  api_key: sk-htxxabglzxtqokjwvfoiidprglsvnqffxshgognjafvgcwov
  api_base: https://api.siliconflow.cn/v1
  description: Expert Agent 专用 Qwen

# 本地 Ollama 配置（如果需要）
ollama-local:
  provider_type: ollama
  model: qwen2.5:7b
  api_base: http://localhost:11434
  description: 本地 Ollama Qwen 模型